# These are supported funding model platforms

github: []
patreon: PegasusHeavyIndustries
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom: []
